# Generated by Django 4.0.3 on 2022-03-28 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelterPrefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPrefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_garden', models.BooleanField()),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelter_prefs', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.shelterprefs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_prefs', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userprefs')),
            ],
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.CheckConstraint(check=models.Q(('user_prefs__isnull', False), ('shelter_prefs__isnull', False), _connector='OR'), name='either_user_prefs_or_shelter_prefs_must_not_be_null'),
        ),
    ]
