# Generated by Django 4.0.3 on 2022-03-28 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='color',
            name='value',
            field=models.TextField(unique=True),
        ),
        migrations.CreateModel(
            name='SpecificAnimalKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(unique=True)),
                ('animal_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.animalkind')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('male', models.BooleanField()),
                ('likes_child', models.BooleanField()),
                ('likes_other_animals', models.BooleanField()),
                ('character', models.ManyToManyField(to='api.character')),
                ('color', models.ManyToManyField(to='api.color')),
                ('size', models.ManyToManyField(to='api.size')),
                ('specific_animal_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.specificanimalkind')),
            ],
        ),
    ]
