# Generated by Django 4.0.3 on 2022-03-28 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_animalkind_character_size_alter_color_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='size',
        ),
        migrations.AddField(
            model_name='animal',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.size'),
            preserve_default=False,
        ),
    ]
