# Generated by Django 4.0.3 on 2022-03-28 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_animal_size_animal_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='character',
            new_name='characters',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='color',
            new_name='colors',
        ),
    ]
