# Generated by Django 4.0.3 on 2022-03-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_character_animal_characters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprefs',
            name='liked_charactes',
            field=models.ManyToManyField(to='api.character'),
        ),
        migrations.AddField(
            model_name='userprefs',
            name='liked_colors',
            field=models.ManyToManyField(to='api.color'),
        ),
        migrations.AddField(
            model_name='userprefs',
            name='liked_kinds',
            field=models.ManyToManyField(to='api.animalkind'),
        ),
    ]
