# Generated by Django 4.0.3 on 2022-04-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_photo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprefs',
            name='prev_animal',
            field=models.IntegerField(default=1),
        ),
    ]
