# Generated by Django 4.0.3 on 2022-04-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_userprefs_prev_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprefs',
            name='prev_animal',
            field=models.IntegerField(null=True),
        ),
    ]
