# Generated by Django 4.0.3 on 2022-04-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_userprefs_prev_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
