# Generated by Django 4.0.3 on 2022-04-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_animal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='randomly_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specificanimalkind',
            name='randomly_generated',
            field=models.BooleanField(default=False),
        ),
    ]
