# Generated by Django 4.0.3 on 2022-04-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_animal_randomly_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprefs',
            name='is_male',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprefs',
            name='likes_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprefs',
            name='likes_other_animals',
            field=models.BooleanField(default=False),
        ),
    ]
