# Generated by Django 4.0.3 on 2022-04-20 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_profile_either_user_prefs_or_shelter_prefs_must_not_be_null_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='shelter',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.shelterprefs'),
        ),
    ]
