# Generated by Django 4.0.3 on 2022-04-23 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_shelterprefs_location_userprefs_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelterprefs',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shelter_prefs', to='api.location'),
        ),
        migrations.AlterField(
            model_name='userprefs',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_prefs', to='api.location'),
        ),
    ]
