# Generated by Django 4.0.3 on 2022-05-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_userprefs_is_male_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprefs',
            name='max_range',
            field=models.IntegerField(null=True),
        ),
    ]
