# Generated by Django 4.0.3 on 2022-05-22 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_userprefs_is_male_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprefs',
            name='liked_animals',
        ),
        migrations.CreateModel(
            name='UserAnimalLikeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('LI', 'Liked'), ('NO', 'Not accepted'), ('AC', 'Accepted')], max_length=2, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.animal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprefs')),
            ],
        ),
    ]
