# Generated by Django 4.0.3 on 2022-04-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_userprefs_liked_animals_animaluserrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprefs',
            name='liked_animals',
            field=models.ManyToManyField(through='api.AnimalUserRelation', to='api.animal'),
        ),
    ]
