# Generated by Django 4.0.3 on 2022-05-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_userprefs_liked_animals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprefs',
            name='liked_animals',
            field=models.ManyToManyField(through='api.UserAnimalLikeRelation', to='api.animal'),
        ),
    ]
