# Generated by Django 4.0.3 on 2022-05-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_userprefs_liked_animals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranimallikerelation',
            name='state',
            field=models.CharField(choices=[('LI', 'Liked'), ('NO', 'Not accepted'), ('AC', 'Accepted')], default='LI', max_length=2),
        ),
    ]
