# Generated by Django 4.0.3 on 2022-04-30 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_userprefs_liked_animals'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='animaluserrelation',
            unique_together={('animal', 'user_prefs')},
        ),
    ]
