# Generated by Django 4.0.3 on 2022-05-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_userprefs_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprefs',
            name='avatar',
            field=models.ImageField(null=True, upload_to='api/avatars'),
        ),
    ]
