# Generated by Django 4.0.3 on 2022-05-31 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_userprefs_max_range'),
        ('api', '0028_userprefs_avatar'),
    ]

    operations = [
    ]
