# Generated by Django 4.0.3 on 2022-05-31 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_animal_shelter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprefs',
            name='max_range',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
